site_name: SIGMA-X 문서
nav:
  - 홈: index.md
  - 시스템 명세: sigma_yaml_structure.md
  - 시스템 다이어그램: sigma_system_diagram.mmd
  - 아키텍처:
      - C4 아키텍처: 1_architecture/c4_architecture.md
      - SIGMA 아키텍처: 1_architecture/SIGMA_Architecture_v1.4.md
      - 배포 뷰: 1_architecture/deployment_view.md
      - 백테스트 흐름: 1_architecture/c3_backtest.md
      - 클래스 다이어그램: 1_architecture/class_diagram.md
  - 컴포넌트 설명: components.md
markdown_extensions:
  - tables
