name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Detect YAML changes
      id: yaml
      run: |
        if git diff --name-only HEAD^ | grep -E '\.ya?ml$'; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Generate diagrams
      if: steps.yaml.outputs.changed == 'true'
      run: |
        python scripts/generate_diagrams.py

    - name: Run scaffold
      if: steps.yaml.outputs.changed == 'true'
      run: |
        python scripts/scaffold.py

    - name: Generate docs
      if: steps.yaml.outputs.changed == 'true'
      run: |
        python scripts/generate_docs.py

    - name: Check generated files committed
      if: steps.yaml.outputs.changed == 'true'
      run: git diff --exit-code

    - name: Run tests
      run: |
        pytest
