jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Detect spec changes
      id: yaml
      run: |
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          base="${{ github.event.pull_request.base.sha }}"
        else
          base="${{ github.event.before }}"
        fi
        if git diff --name-only "$base" "$GITHUB_SHA" | grep -E '^specs/.*\.ya?ml$'; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        else
          echo "changed=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Install mermaid-cli
      run: |
        npm install -g @mermaid-js/mermaid-cli

    - name: Generate diagrams
      if: steps.yaml.outputs.changed == 'true'
      run: |
        python scripts/generate_diagrams.py

    - name: Build diagram images
      run: |
        bash docs/scripts/gen_diagrams.sh

    - name: Run scaffold
      if: steps.yaml.outputs.changed == 'true'
      run: |
        python scripts/scaffold.py

    - name: Generate docs
      if: steps.yaml.outputs.changed == 'true'
      run: |
        python scripts/generate_docs.py

    - name: Check generated files committed
      if: steps.yaml.outputs.changed == 'true'
      run: git diff --exit-code

    - name: Run tests
      run: |
        pytest
